apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fan-manager
  namespace: fan-manager
  labels:
    app: fan-manager
spec:
  selector:
    matchLabels:
      app: fan-manager
  template:
    metadata:
      labels:
        app: fan-manager
        date: "2023-10-03"
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Exists
          effect: NoSchedule
        - key: "node-role.kubernetes.io/control-plane"
          operator: Exists
          effect: NoSchedule
      containers:
        - name: fan-manager
          image: ghcr.io/0xc9c3/radxa-x4-cluster/fan-manager:main
          imagePullPolicy: Always
          args: [ "-p", "/dev/ttyS0" ,
                  "-s", "1:10",
                  "-s", "30:20",
                  "-s", "40:25",
                  "-s", "45:35",
                  "-s", "50:40",
                  "-s", "55:45",
                  "-s", "65:55",
                  "-s", "70:60",
                  "-s", "80:100"
          ]
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          securityContext:
            privileged: true
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fan-manager
spec:
  selector:
    matchLabels:
      app: fan-manager
  podMetricsEndpoints:
    - port: metrics
      interval: 10s